// src/config/formConfig.ts

import { FormConfig } from '../types/form.types';

const formConfig: FormConfig = {
  title: 'Risk Assessment Questionnaire',
  description: 'Complete this comprehensive questionnaire to assess your organizational risk profile',
  sections: [
    {
      id: 'compliance',
      title: 'Compliance Assessment',
      description: 'Evaluate your compliance posture and certifications',
      questions: [
        {
          id: 'q1',
          type: 'select',
          label: 'Do you have SOC2 certification?',
          description: 'ISO/IEC 27001 or SOC2 Type II',
          options: ['Yes', 'No', 'In Progress'],
          required: true,
          riskWeight: 4,
          conditional: null,
          helpText: 'SOC2 certification demonstrates commitment to security controls',
        },
        {
          id: 'q2',
          type: 'file',
          label: 'Upload compliance certificate',
          description: 'PDF copy of your certification',
          accept: '.pdf',
          maxSize: 10,
          required: false,
          riskWeight: 5,
          conditional: {
            questionId: 'q1',
            answer: 'Yes',
          },
          helpText: 'Upload PDF file of your certification document',
        },
        {
          id: 'q3',
          type: 'number',
          label: 'How many certifications do you have?',
          required: false,
          riskWeight: 2,
          min: 0,
          max: 10,
          helpText: 'Including ISO 27001, SOC2, GDPR, HIPAA, etc.',
          conditional: null,
        },
      ],
    },
    {
      id: 'financial',
      title: 'Financial Status',
      description: 'Provide information about your financial stability',
      questions: [
        {
          id: 'q4',
          type: 'select',
          label: 'Is your financial statement audited?',
          options: ['Yes', 'No', 'Not Applicable'],
          required: true,
          riskWeight: 5,
          conditional: null,
          helpText: 'Third-party audited financial statements indicate financial transparency',
        },
        {
          id: 'q5',
          type: 'number',
          label: 'Annual revenue (in USD millions)',
          required: true,
          riskWeight: 3,
          min: 0,
          max: 10000,
          helpText: 'Approximate annual revenue in millions',
          conditional: null,
        },
        {
          id: 'q6',
          type: 'text',
          label: 'Explain any recent financial issues or risks',
          required: false,
          riskWeight: 4,
          maxLength: 500,
          conditional: {
            questionId: 'q4',
            answer: 'No',
          },
          helpText: 'Provide context if audited financials are not available',
        },
      ],
    },
    {
      id: 'operational',
      title: 'Operational Readiness',
      description: 'Assessment of operational controls and processes',
      questions: [
        {
          id: 'q7',
          type: 'checkbox',
          label: 'Which security controls do you have in place?',
          options: [
            'Data Encryption',
            'Access Control',
            'Incident Response Plan',
            'Regular Security Audits',
            'Employee Security Training',
            'Backup & Recovery',
          ],
          required: true,
          riskWeight: 3,
          helpText: 'Select all controls that are implemented',
          conditional: null,
        },
        {
          id: 'q8',
          type: 'date',
          label: 'Date of last security audit',
          required: false,
          riskWeight: 2,
          conditional: {
            questionId: 'q7',
            answer: 'Regular Security Audits',
            operator: 'contains',
          },
          helpText: 'When was your last security assessment conducted?',
        },
        {
          id: 'q9',
          type: 'select',
          label: 'Do you have a documented incident response plan?',
          options: ['Yes', 'No', 'In Development'],
          required: true,
          riskWeight: 4,
          helpText: 'Documented procedures for handling security incidents',
          conditional: null,
        },
      ],
    },
    {
      id: 'cybersecurity',
      title: 'Cybersecurity Posture',
      description: 'Evaluate current cybersecurity measures',
      questions: [
        {
          id: 'q10',
          type: 'select',
          label: 'Do you have cybersecurity insurance?',
          options: ['Yes', 'No'],
          required: true,
          riskWeight: 4,
          helpText: 'Cyber liability or professional liability insurance',
          conditional: null,
        },
        {
          id: 'q11',
          type: 'text',
          label: 'Explain why you don\'t have cybersecurity insurance',
          required: false,
          riskWeight: 5,
          maxLength: 500,
          conditional: {
            questionId: 'q10',
            answer: 'No',
          },
          helpText: 'Provide reason if insurance is not in place',
        },
        {
          id: 'q12',
          type: 'number',
          label: 'Number of security incidents in past 12 months',
          required: true,
          riskWeight: 5,
          min: 0,
          max: 100,
          helpText: 'Include attempted and successful breaches',
          conditional: null,
        },
      ],
    },
  ],
};

export default formConfig;